// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AlignRefAndRead
List AlignRefAndRead(std::string ref, List read, bool useAffine);
RcppExport SEXP ccsviewr_AlignRefAndRead(SEXP refSEXP, SEXP readSEXP, SEXP useAffineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ref(refSEXP);
    Rcpp::traits::input_parameter< List >::type read(readSEXP);
    Rcpp::traits::input_parameter< bool >::type useAffine(useAffineSEXP);
    rcpp_result_gen = Rcpp::wrap(AlignRefAndRead(ref, read, useAffine));
    return rcpp_result_gen;
END_RCPP
}
// AlnsToDataFrame
List AlnsToDataFrame(List alns);
RcppExport SEXP ccsviewr_AlnsToDataFrame(SEXP alnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type alns(alnsSEXP);
    rcpp_result_gen = Rcpp::wrap(AlnsToDataFrame(alns));
    return rcpp_result_gen;
END_RCPP
}
