// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AlignRefAndRead
List AlignRefAndRead(std::string ref, List read);
RcppExport SEXP ccsviewr_AlignRefAndRead(SEXP refSEXP, SEXP readSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type ref(refSEXP);
    Rcpp::traits::input_parameter< List >::type read(readSEXP);
    __result = Rcpp::wrap(AlignRefAndRead(ref, read));
    return __result;
END_RCPP
}
