# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Align a read and a reference window.  Both the forward and reverse direction
#' of the read will be  aligned, and only the highest scoring alignment will be
#' returned.
#'
#' @param ref A string that is the reference window we are aligning to.
#' @param read A list with elements name/read.
#'
#' @return Returns a list with the aligned read, ref and score
#' @export
AlignRefAndRead <- function(ref, read, useAffine = FALSE) {
    .Call('_ccsviewr_AlignRefAndRead', PACKAGE = 'ccsviewr', ref, read, useAffine)
}

#' Takes a list of pairwise alignments and generates a data frame with the MSA
#' sequence. The reference sequence is determined from the first alignment in
#' the list. All reads are expanded by adding enough inserts to account for all
#' of them.
#'
#' @param ref A string that is the reference window we are aligning to.
#' @param read A list with elements name/read.
#'
#' @return Returns a list with the aligned read, ref and score
#' @export
AlnsToDataFrame <- function(alns) {
    .Call('_ccsviewr_AlnsToDataFrame', PACKAGE = 'ccsviewr', alns)
}

